version: '3'

services:
  anyway:
    build: .
    container_name: anyway
    image: hasadna/anyway:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://anyway:anyway@db/anyway
    volumes:
      - .:/anyway
    restart: always
    depends_on:
      - db

  db:
    build: db_docker
    container_name: db
    environment:
      - POSTGRES_PASSWORD=anyway
      - POSTGRES_USER=anyway
      - POSTGRES_DB=anyway
      - DB_DUMP_PATH=/tmp/anyway_public.pgdump
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "9876:5432"
    restart: always

volumes:
  db_data:
